delete from sys_login_log;
delete from sys_permission;
delete from sys_role;
delete from sys_user;
delete from sys_settings;
delete from sys_re_role_permission;


INSERT INTO sys_permission VALUES ('3', '46', '用户管理', 'admin/user', '1', '1', '1', 'fa-user', '');
INSERT INTO sys_permission VALUES ('4', '46', '角色管理', 'admin/role', '2', '1', '1', 'fa-user-secret', '');
INSERT INTO sys_permission VALUES ('5', '46', '权限管理', 'admin/permission', '3', '1', '1', 'fa-key', '');
INSERT INTO sys_permission VALUES ('10', '3', '用户添加', 'admin/user/edit', '2', '1', '1', 'fa-plus-circle blue', 'sys:user:edit');
INSERT INTO sys_permission VALUES ('11', '3', '用户禁用', 'admin/user/enable', '4', '1', '1', 'fa-lock orange', 'sys:user:enable');
INSERT INTO sys_permission VALUES ('12', '3', '用户启用', 'admin/user/enable', '3', '1', '1', 'fa-unlock green', 'sys:user:enable');
INSERT INTO sys_permission VALUES ('13', '3', '用户删除', 'admin/user/delete', '1', '1', '1', 'fa-trash-o red', 'sys:user:delete');
INSERT INTO sys_permission VALUES ('14', '3', '重置密码', 'admin/user/resetPassword', '5', '1', '1', 'fa-key grey', 'sys:user:resetPassword');
INSERT INTO sys_permission VALUES ('15', '3', '分配角色', 'admin/user/allocate', '6', '1', '1', 'fa-cog grey', 'sys:user:allocate');
INSERT INTO sys_permission VALUES ('16', '4', '角色新增', 'admin/role/edit', '5', '1', '1', 'fa-plus-circle blue', 'sys:role:edit');
INSERT INTO sys_permission VALUES ('17', '4', '角色禁用', 'admin/role/enable', '4', '1', '1', 'fa-lock orange', 'sys:role:enable');
INSERT INTO sys_permission VALUES ('18', '4', '角色启用', 'admin/role/enable', '3', '1', '1', 'fa-unlock green', 'sys:role:enable');
INSERT INTO sys_permission VALUES ('19', '4', '角色删除', 'admin/role/delete', '2', '1', '1', 'fa-trash-o red', 'sys:role:delete');
INSERT INTO sys_permission VALUES ('20', '4', '角色授权', 'admin/role/allocate', '1', '1', '1', 'fa-cog grey', 'sys:role:allocate');
INSERT INTO sys_permission VALUES ('24', '4', '角色列表', 'admin/role', '6', '1', '1', '', 'sys:role:list');
INSERT INTO sys_permission VALUES ('25', '5', '权限列表', 'admin/permission/nodes', '1', '1', '1', '', 'sys:permission:list');
INSERT INTO sys_permission VALUES ('27', '3', '用户编辑', 'admin/user/save', '1', '1', '1', '', 'sys:user:edit');
INSERT INTO sys_permission VALUES ('28', '4', '角色编辑', 'admin/role/save', '1', '1', '1', '', 'sys:role:edit');
INSERT INTO sys_permission VALUES ('29', '5', '权限保存', 'admin/permission/save', '1', '1', '1', '', 'sys:permission:edit');
INSERT INTO sys_permission VALUES ('30', '5', '权限删除', 'admin/permission/delete', '1', '1', '1', '', 'sys:permission:delete');
INSERT INTO sys_permission VALUES ('44', '5', '权限添加', 'admin/permission/save', '4', '1', '1', '', 'sys:permission:edit');
INSERT INTO sys_permission VALUES ('45', null, '系统管理', 'sys', '1', '1', '1', 'fa-cogs', '');
INSERT INTO sys_permission VALUES ('46', null, '用户中心', 'user', '2', '1', '1', 'fa-user-circle', '');
INSERT INTO sys_permission VALUES ('48', '45', '登录日志', 'admin/loginlog', '1', '1', '1', 'fa-history', 'sys:authlog');
INSERT INTO sys_permission VALUES ('49', '3', '用户列表', 'sys/user', '7', '1', '1', '', 'sys:user:list');
INSERT INTO sys_permission VALUES ('50', '48', '日志清理', 'admin/loginlog/delete', '1', '1', '1', '', 'sys:loginlog:delete');
INSERT INTO sys_permission VALUES ('51', '48', '日志列表', 'admin/loginlog', '2', '1', '1', '', 'sys:loginlog:list');
INSERT INTO sys_permission VALUES ('52', '46', '在线用户', 'admin/online', '4', '1', '1', 'fa-crop', '');
INSERT INTO sys_permission VALUES ('53', '52', '在线用户列表', 'admin/online/page', '1', '1', '1', '', 'sys:online:list');
INSERT INTO sys_permission VALUES ('54', '52', '用户下线', 'admin/online/kickout', '2', '1', '1', '', 'sys:online:kill');
INSERT INTO sys_permission VALUES ('55', '52', '在线用户刷新', 'admin/online', '3', '1', '1', '', 'sys:online:refresh');
INSERT INTO sys_permission VALUES ('56', '45', '系统设置', 'admin/settings', '2', '1', '1', 'fa-gear', '');
INSERT INTO sys_re_role_permission VALUES ('381', '4', '45');
INSERT INTO sys_re_role_permission VALUES ('382', '4', '48');
INSERT INTO sys_re_role_permission VALUES ('383', '4', '50');
INSERT INTO sys_re_role_permission VALUES ('384', '4', '51');
INSERT INTO sys_re_role_permission VALUES ('385', '4', '46');
INSERT INTO sys_re_role_permission VALUES ('386', '4', '3');
INSERT INTO sys_re_role_permission VALUES ('387', '4', '49');
INSERT INTO sys_re_role_permission VALUES ('388', '4', '4');
INSERT INTO sys_re_role_permission VALUES ('389', '4', '24');
INSERT INTO sys_re_role_permission VALUES ('390', '4', '5');
INSERT INTO sys_re_role_permission VALUES ('391', '4', '25');
INSERT INTO sys_re_role_permission VALUES ('453', '1', '45');
INSERT INTO sys_re_role_permission VALUES ('454', '1', '48');
INSERT INTO sys_re_role_permission VALUES ('455', '1', '50');
INSERT INTO sys_re_role_permission VALUES ('456', '1', '51');
INSERT INTO sys_re_role_permission VALUES ('457', '1', '56');
INSERT INTO sys_re_role_permission VALUES ('458', '1', '46');
INSERT INTO sys_re_role_permission VALUES ('459', '1', '3');
INSERT INTO sys_re_role_permission VALUES ('460', '1', '13');
INSERT INTO sys_re_role_permission VALUES ('461', '1', '27');
INSERT INTO sys_re_role_permission VALUES ('462', '1', '10');
INSERT INTO sys_re_role_permission VALUES ('463', '1', '12');
INSERT INTO sys_re_role_permission VALUES ('464', '1', '11');
INSERT INTO sys_re_role_permission VALUES ('465', '1', '14');
INSERT INTO sys_re_role_permission VALUES ('466', '1', '15');
INSERT INTO sys_re_role_permission VALUES ('467', '1', '49');
INSERT INTO sys_re_role_permission VALUES ('468', '1', '4');
INSERT INTO sys_re_role_permission VALUES ('469', '1', '20');
INSERT INTO sys_re_role_permission VALUES ('470', '1', '28');
INSERT INTO sys_re_role_permission VALUES ('471', '1', '19');
INSERT INTO sys_re_role_permission VALUES ('472', '1', '18');
INSERT INTO sys_re_role_permission VALUES ('473', '1', '17');
INSERT INTO sys_re_role_permission VALUES ('474', '1', '16');
INSERT INTO sys_re_role_permission VALUES ('475', '1', '24');
INSERT INTO sys_re_role_permission VALUES ('476', '1', '5');
INSERT INTO sys_re_role_permission VALUES ('477', '1', '25');
INSERT INTO sys_re_role_permission VALUES ('478', '1', '29');
INSERT INTO sys_re_role_permission VALUES ('479', '1', '30');
INSERT INTO sys_re_role_permission VALUES ('480', '1', '44');
INSERT INTO sys_re_role_permission VALUES ('481', '1', '52');
INSERT INTO sys_re_role_permission VALUES ('482', '1', '53');
INSERT INTO sys_re_role_permission VALUES ('483', '1', '54');
INSERT INTO sys_re_role_permission VALUES ('484', '1', '55');
INSERT INTO sys_re_user_role VALUES ('14', '2', '1');
INSERT INTO sys_re_user_role VALUES ('15', '3', '4');
INSERT INTO sys_role VALUES ('1', '管理员', 'admin', '999', '单点登录管理员角色', '1');
INSERT INTO sys_role VALUES ('4', '测试', 'test', '1', 'demo测试角色', '1');
INSERT INTO sys_settings VALUES ('site_name', '百灵权限管理系统 ');
INSERT INTO sys_settings VALUES ('meta_description', '百灵权限管理系统，是一款构建在用户、角色、权限、日志、在线用户、用户下线之基础上等开源权限管理项目');
INSERT INTO sys_settings VALUES ('site_icp', '京ICP证030173号');
INSERT INTO sys_settings VALUES ('mailport', '25');
INSERT INTO sys_settings VALUES ('mailauth_username', 'test@163.com');
INSERT INTO sys_settings VALUES ('mailauth_password', '123456');
INSERT INTO sys_settings VALUES ('mult_login', '0');
INSERT INTO sys_settings VALUES ('kill_login', '1');
INSERT INTO sys_settings VALUES ('error_times_login', '2');
INSERT INTO sys_settings VALUES ('site_copyright', '蝴蝶飞飞');
INSERT INTO sys_settings VALUES ('site_keywords', '百灵，权限，用户， 角色');
INSERT INTO sys_user VALUES ('2', 'admin', '6b1a2c3a1615cf2ff8a581218bab703a', '192.168.1.122', '2017-06-12 15:58:10', '2', '2015-06-02 11:31:56', '1');
INSERT INTO sys_user VALUES ('3', 'test', '6b1a2c3a1615cf2ff8a581218bab703a', null, null, '0', '2017-06-12 17:22:44', '1');
